config/routes.rb
Podium::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'pages#show', defaults: {id: 'home'}

  namespace :api do
    resources :gallerys, only: [:show, :destroy], :defaults => { :format => 'json' } do
      resources :images, only: [:index], :defaults => { :format => 'json' }
    end
    resources :images, only: [:create, :show, :destroy], :defaults => { :format => 'json' }
    endpoint = Dragonfly.app.endpoint { |params, app|
      app.fetch_file("public/system/dragonfly/#{Rails.env}/#{params[:file]}").thumb(params[:size]) 
    }   
    get "image" => endpoint, as: :thumb
    post 'login' => 'sessions#create', as: :login
    post 'logout' => 'sessions#destroy', as: :logout

    get 'events' => 'events#index', as: :events, :defaults => { :format => 'json', :parent => 'events' }
    get 'announces' => 'events#index', as: :announces, :defaults => { :format => 'json', :parent => 'announces' }
    get 'announces/nearly' => 'events#nearly', as: :nearly_announces, :defaults => { :format => 'json', :parent => 'announces' }
    post 'request' => 'cards#card_request', :defaults => { :format => 'json' }
  end

  # post '/upload' => 'upload#create', as: :upload

  %w(events promotions).each do |name|
    scope "/#{name}" do
      resources :events, defaults: {parent: name}, path: '', as: name do
      end
    end
  end

  scope module: :events do
    resources :events, only: [] do
      resources :images, only: [:index, :destroy] do
        post :bulk_create, on: :collection
      end
    end
  end

  # scope parent: 'events'
  # resources 'events', defaults: { parent: 'events' } 
  #   resources :promotions, defaults: { parent: 'promotions' }, controller: :events
  resources 'announces', defaults: { parent: 'announces' }

  resources :background_images, only: [:index, :destroy] do
    post :bulk_create, on: :collection
  end

  resource :adult_confirmation, controller: :adult_confirmation, only: :show do
    get :confirm, on: :member
  end

  def page_mode(url, action, name, mode=:get)
    match "*id/#{url}" => action, via: [mode], as: name
  end

  post '/pages' => 'pages#update', as: :update_page
  post '/pages/preview' => 'pages#preview', as: :preview_page

  page_mode('menu_form', 'menu#form', :new_menu)
  page_mode('menu_form', 'menu#create', :create_menu, :post)
  page_mode('menu_form/(:menu_id)', 'menu#form', :edit_menu)
  page_mode('menu_form/(:menu_id)', 'menu#update', :update_menu, :put)
  page_mode('menu_form/(:menu_id)', 'menu#destroy', :destroy_menu, :delete)

  page_mode('card_form', 'cards#form', :new_card)
  page_mode('card_form', 'cards#create', :create_card, :post)
  page_mode('card_form/(:card_id)', 'cards#form', :edit_card)
  page_mode('card_form/(:card_id)', 'cards#update', :update_card, :put)
  page_mode('card_form/(:card_id)', 'cards#destroy', :destroy_card, :delete)

  match '*id' => 'pages#show', via: [:get], as: :page
  
end

app/views/shared/_footer.html.haml
.footer.container
  .copyright.col-md-3
    © 2016 ОФИЦИАЛЬНЫЙ САЙТ
    %br
    GENTELMEN'S CLUB «PODIUM»    
  .menu.col-md-7
    = Page.template_text 'menu'    
  .madein.col-md-2
    Сделано в Контрасте 

app/views/shared/_head.html.haml
- social_networks = {vkontakte: 'http://vk.com/podium_hall', facebook: 'https://www.facebook.com/profile.php?id=100005544825110', youtube: 'http://www.youtube.com/channel/UCdxtz_TO_u6icFVsxzBT7fA'}

.head.container
  .row
    .logo.col-md-3
      = link_to image_tag('/assets/logo.png'), root_path
    .phones.col-md-4
      %span +7 919 063 8000
      = "/"
      %span +7 (4822) 424 758
      
    .login.col-md-2
      .social-icons
        - social_networks.each do |name, url|
          = link_to '', url, class: ['social-icon', name], target: '_blank'
    -unless current_user
      .age.login_button.col-md-3
        %strong 18+
        Только для 
        %br
        совершеннолетних 
    -else 
      .age.logout_button.col-md-3
        Выход


  .menu
    -# = render 'shared/menu'
    = Page.template_text 'menu'
  - if current_user
    .menu
      %ul
        %li
          = link_to 'Фоновые изображения', background_images_path

app/views/shared/_menu.html.haml
%ul
  - Page.in_menu.each do |page|
    %li
      - next unless page
      - if page.children.present?
        = link_to page.title, 'javascript:void()'
        %ul
          - page.children.each do |page|
            %li= link_to page.title, page.url
      - else
        = link_to page.title, page.url

app/views/shared/_slider.html.haml
.slider_block
  .slider
    = yield
  %div{style: "display: block;",class: "navi prev"}
  %div{style: "display: block;",class: "navi next"}
  .clearfix

:coffee
  $ ->
    $el = $('.slider_block')
    $('.slider', $el).carouFredSel
      items: 3
      width: 840
      align: 'center'
      prev: 
        button: $('.prev', $el)
      next: 
        button: $('.next', $el)
      scroll:
        items: 1
      auto:
        play: false

app/views/shared/_upload_form.html.haml
=form_for Photo.new, url: api_images_path, :html => { :multipart => true, :id => "fileupload"  } do |f|
  .row.fileupload-buttonbar
    %span.btn.btn-success.fileinput-button
      %i.icon-plus.icon-white
      %span Добавить файлы
      = f.file_field 'image', {multiple: true}
    %button.btn.btn-primary.start{type: :submit}
      %i.icon-upload.icon-white
      %span Начать закачку

    %button.btn.btn-warning.cancel{type: :reset}
      %i.icon-ban-circle.icon-white
      %span Отмена

    %button.btn.btn-danger.delete{type: :button}
      %i.icon-trash.icon-white
      %span Удалить
          
  %table{class:"table "}
    %tbody{class:"files", 'data-toggle'=>"modal-gallery", 'data-target'=>"#modal-gallery"}

  .progress.progress-success.progress-striped.active.fade
    .bar{style:"width:0%"}

=render 'shared/upload_templates'

:coffeescript
  $ ->
    $('#fileupload').fileupload();

app/views/shared/_upload_templates.html.haml
:plain
  <!-- The template to display files available for upload -->
  <script id="template-upload" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
      <td class="preview"><span class="fade"></span></td>
      <td class="name"><span>{%=file.name%}</span></td>
      <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
      {% if (file.error) { %}
      <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
      {% } else if (o.files.valid && !i) { %}
      <td>
        <div class="progress progress-success progress-striped active"><div class="bar" style="width:0%;"></div></div>
      </td>
      <td class="start">{% if (!o.options.autoUpload) { %}
        <button class="btn btn-primary">
          <i class="icon-upload icon-white"></i>
          <span>{%=locale.fileupload.start%}</span>
        </button>
        {% } %}</td>
      {% } else { %}
      <td colspan="2"></td>
      {% } %}
      <td class="cancel">{% if (!i) { %}
        <button class="btn btn-warning">
          <i class="icon-ban-circle icon-white"></i>
          <span>{%=locale.fileupload.cancel%}</span>
        </button>
        {% } %}</td>
    </tr>
    {% } %}
  </script>
  <!-- The template to display files available for download -->
  <script id="template-download" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
      <tr class="template-download fade">
        {% if (file.error) { %}
          <td></td>
          <td class="name"><span>{%=file.name%}</span></td>
          <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
          <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
          {% } else { %}
          <td class="preview">{% if (file.thumbnail_url) { %}
            <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.thumbnail_url%}"></a>
            {% } %}</td>
          <td class="name">
            <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
          </td>
          <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
          <td colspan="2"></td>
          {% } %}
        <td class="delete">
          <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
            <i class="icon-trash icon-white"></i>
            <span>{%=locale.fileupload.destroy%}</span>
          </button>
          <input type="checkbox" name="delete" value="1">
        </td>
      </tr>
      {% } %}
  </script>