config/routes.rb
Podium::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'pages#show', defaults: {id: 'home'}

  namespace :api do
    resources :gallerys, only: [:show, :destroy], :defaults => { :format => 'json' } do
      resources :images, only: [:index], :defaults => { :format => 'json' }
    end
    resources :images, only: [:create, :show, :destroy], :defaults => { :format => 'json' }
    endpoint = Dragonfly.app.endpoint { |params, app|
      app.fetch_file("public/system/dragonfly/#{Rails.env}/#{params[:file]}").thumb(params[:size]) 
    }   
    get "image" => endpoint, as: :thumb
    post 'login' => 'sessions#create', as: :login
    post 'logout' => 'sessions#destroy', as: :logout

    get 'events' => 'events#index', as: :events, :defaults => { :format => 'json', :parent => 'events' }
    get 'announces' => 'events#index', as: :announces, :defaults => { :format => 'json', :parent => 'announces' }
    get 'announces/nearly' => 'events#nearly', as: :nearly_announces, :defaults => { :format => 'json', :parent => 'announces' }
    post 'request' => 'cards#card_request', :defaults => { :format => 'json' }
  end

  # post '/upload' => 'upload#create', as: :upload

  %w(events promotions).each do |name|
    scope "/#{name}" do
      resources :events, defaults: {parent: name}, path: '', as: name do
      end
    end
  end

  scope module: :events do
    resources :events, only: [] do
      resources :images, only: [:index, :destroy] do
        post :bulk_create, on: :collection
      end
    end
  end

  # scope parent: 'events'
  # resources 'events', defaults: { parent: 'events' } 
  #   resources :promotions, defaults: { parent: 'promotions' }, controller: :events
  resources 'announces', defaults: { parent: 'announces' }

  resources :background_images, only: [:index, :destroy] do
    post :bulk_create, on: :collection
  end

  resource :adult_confirmation, controller: :adult_confirmation, only: :show do
    get :confirm, on: :member
  end

  def page_mode(url, action, name, mode=:get)
    match "*id/#{url}" => action, via: [mode], as: name
  end

  post '/pages' => 'pages#update', as: :update_page
  post '/pages/preview' => 'pages#preview', as: :preview_page

  page_mode('menu_form', 'menu#form', :new_menu)
  page_mode('menu_form', 'menu#create', :create_menu, :post)
  page_mode('menu_form/(:menu_id)', 'menu#form', :edit_menu)
  page_mode('menu_form/(:menu_id)', 'menu#update', :update_menu, :put)
  page_mode('menu_form/(:menu_id)', 'menu#destroy', :destroy_menu, :delete)

  page_mode('card_form', 'cards#form', :new_card)
  page_mode('card_form', 'cards#create', :create_card, :post)
  page_mode('card_form/(:card_id)', 'cards#form', :edit_card)
  page_mode('card_form/(:card_id)', 'cards#update', :update_card, :put)
  page_mode('card_form/(:card_id)', 'cards#destroy', :destroy_card, :delete)

  match '*id' => 'pages#show', via: [:get], as: :page
  
end

app/controllers/api/events_controller.rb
# encoding: utf-8
class Api::EventsController < ApplicationController
  
  def index
    @events = Post.where(parent: params[:parent]).order('datetime DESC').limit(2)
    render json: @events.as_json({only: [:id, :image_uid, :title, :preview], methods: [:day, :month]})
  end

  def nearly
    @events = Post.where({parent: params[:parent]}).where('datetime > NOW()').order('datetime').limit(10)
    render json: @events.as_json({only: [:id, :image_uid, :title, :preview], methods: [:day, :month]})
  end

end

app/controllers/events/images_controller.rb
class Events::ImagesController < ApplicationController
  before_filter :require_login
  inherit_resources

  before_filter :load_event, only: [:bulk_create, :destroy]

  respond_to :js, only: [:destroy]

  def bulk_create
    files = []
    params[:images].each do |bg_image_data|
      bg_image = Image.new(image: bg_image_data, imageable: @event).decorate
      if bg_image.save
        files << bg_image.to_jq_upload
      else
        render :json => [{:error => "custom_failure"}], :status => 304
        return
      end
    end
    render json: {files: files}, status: :created
  end

  def destroy
    @image = @event.images.find(params[:id])
    @image.destroy
    respond_with @image, location: nil
  end

private

  def load_event
    @event = Post.find(params[:event_id])
  end
end

app/controllers/events_controller.rb
# encoding: utf-8
class EventsController < ApplicationController

  def index
    @events = Post.where(parent: params[:parent]).order('datetime DESC').limit(10)
  end
  
  def new
    authorize! :edit, Post
    @event = Post.new 
  end

  def create
    authorize! :edit, Post
    @post = Post.new params[:post]
    @post.parent = params[:parent]
    @post.save
    redirect_to collection_path
  end

  def edit
    authorize! :edit, Post
    @event = Post.find(params[:id])
  end

  def update
    authorize! :edit, Post
    post = Post.find(params[:id])
    if post.update_attributes(params[:post])
      redirect_to resource_path(post)
    else 
      render "edit"  
    end
  end

  def destroy
    authorize! :edit, Post
    Post.where(id: params[:id]).destroy_all
    render json: 'OK'
  end

  def show
    @event = Post.find(params[:id])
  end

private

  def collection_path
    send("#{params[:parent]}_path")
  end

  def resource_path(event)
    send("#{params[:parent].singularize}_path", event)
  end
end 

app/views/events/_events_list.html.haml
.events_list
  = render layout: 'shared/slider' do
    - @events.each do |event|
      .item
        = link_to send("#{params[:parent].singularize}_path", event) do
          .image
            - if event.image_stored?
              =image_tag event.image.thumb('370x560').url 
          .date 
            %span.day= event.day
            %span.month= event.month
          .title
            = event.title
          .preview
            = event.preview

app/views/events/_form.html.haml
.form-group
  %label Заголовок
  = f.text_field :title, class: 'form-control'
.form-group
  %label Краткое содержание  
  = f.text_area :preview, cols: 10, rows: 5, class: 'form-control'
.form-group
  %label Полное содержание
  = f.cktext_area :source, cols: 10, rows: 20, class: 'form-control'
.form-group
  %label Изображение  
  = f.file_field :image
.form-group.datetime_line
  %label Дата и время начала мероприятия: 
  = f.datetime_select :datetime, class: 'form-control'

.form-group
  = f.submit "Сохранить", class: 'btn btn-primary'

app/views/events/edit.html.haml
.content_block.container
  = form_for @event, :url => event_path(@event) do |f|
    = render :partial => "form", :locals => {:f => f}

  - if params[:parent] == 'events'
    = form_tag bulk_create_event_images_path(@event), method: :post, multipart: true, id: 'bg_image_fileupload' do
      .row.fileupload-buttonbar
        %spanbtn.btn-success.fileinput-button
          %i.icon-plus.icon-white
          %span Добавить файлы
          = file_field_tag 'images[]', multiple: true

    .background_images
      - @event.images.each do |image|
        .background_image{'data-image-id' => image.id}
          = image_tag image.image.thumb.url
          %span
            = link_to 'x', event_image_path(@event, image), method: :delete, remote: true

:coffee
  $ ->
    $bg_images = $('.background_images')
    $file_upload = $('#bg_image_fileupload')

    if $file_upload
      $file_upload.fileupload
        dataType: 'json'
        autoUpload: true
        uploadTemplateId: false
        downloadTemplateId: false
        done: (_, data) ->
          if data && data.result && data.result.files
            for file in data.result.files
              add_image(file)


    add_image = (file) ->
      $item = $('<div/>')
      link_html = '<a href="' + file.delete_url + '" data-method="delete" data-remote="true" rel="nofollow">x</a>'
      $item
        .addClass('background_image')
        .attr('data-image-id', file.id)
      $item
        .append $('<img/>').attr('src', file.thumbnail_url)
        .append $('<span/>').html(link_html)
      $('.background_images').append $item

:sass
  .background_image
    position:relative
    float: left
    margin: 0 10px 10px 0

    span
      position:absolute
      right: -4px
      top: -10px

app/views/events/index.html.haml
.content_block.container
  %h1= {'events' => 'События', 'promotions' => 'Акции'}[params[:parent]]
  -if can? :edit, Post
    .top_controls
      = link_to 'Добавить пост', send("new_#{params[:parent].singularize}_path"), class: 'btn btn-success'
  = render 'events_list'

app/views/events/new.html.haml
.content_block.container
  %h1 Добавление
  = form_for @event, :url => send("#{params[:parent]}_path") do |f|
    = render :partial => "form", :locals => {:f => f}

app/views/events/show.html.slim
- edit_resource_url = send("edit_#{params[:parent].singularize}_path", @event)

.event.content_block.container
  h1= @event.title
  .text
    -if @event.image_stored?
      .event_image
        = image_tag @event.image.thumb('400x400').url
    .date= @event.datetime
    == @event.source
  .links
    - if can? :edit, Post
      = link_to 'Редактировать', edit_resource_url, class: 'btn btn-success'
      = link_to 'Удалить', 'javascript:;', class: 'delete_link btn btn-danger', data_id: @event.id

  - if @event.images.present?
  .gallery_widget

coffee:
  $ ->
    $('.delete_link').on 'click', ->
      id = $(this).attr('data_id')
      if(confirm('Удалить новость?'))
        $.ajax
          url: Routes.event_path(id)
          type: 'DELETE'
          success: ->
            window.location.replace(Routes.events_path)

- if params[:parent] == 'events' && @event.images.present?
  - images = @event.images.map {|i| {id: i.id, uid: "event-image-#{i.id}", url: i.image.slider_mini.url, normal_url: i.image.slider_normal.url} }

  javascript:
    window.event_images = #{images.to_json.html_safe}

  coffee:
    $ ->
      $el = $('.gallery_widget')
      if $el.length > 0
        gallery = new App.EventGallery($el, hide_editor: true, images: window.event_images)