config/routes.rb
Podium::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'pages#show', defaults: {id: 'home'}

  namespace :api do
    resources :gallerys, only: [:show, :destroy], :defaults => { :format => 'json' } do
      resources :images, only: [:index], :defaults => { :format => 'json' }
    end
    resources :images, only: [:create, :show, :destroy], :defaults => { :format => 'json' }
    endpoint = Dragonfly.app.endpoint { |params, app|
      app.fetch_file("public/system/dragonfly/#{Rails.env}/#{params[:file]}").thumb(params[:size]) 
    }   
    get "image" => endpoint, as: :thumb
    post 'login' => 'sessions#create', as: :login
    post 'logout' => 'sessions#destroy', as: :logout

    get 'events' => 'events#index', as: :events, :defaults => { :format => 'json', :parent => 'events' }
    get 'announces' => 'events#index', as: :announces, :defaults => { :format => 'json', :parent => 'announces' }
    get 'announces/nearly' => 'events#nearly', as: :nearly_announces, :defaults => { :format => 'json', :parent => 'announces' }
    post 'request' => 'cards#card_request', :defaults => { :format => 'json' }
  end

  # post '/upload' => 'upload#create', as: :upload

  %w(events promotions).each do |name|
    scope "/#{name}" do
      resources :events, defaults: {parent: name}, path: '', as: name do
      end
    end
  end

  scope module: :events do
    resources :events, only: [] do
      resources :images, only: [:index, :destroy] do
        post :bulk_create, on: :collection
      end
    end
  end

  # scope parent: 'events'
  # resources 'events', defaults: { parent: 'events' } 
  #   resources :promotions, defaults: { parent: 'promotions' }, controller: :events
  resources 'announces', defaults: { parent: 'announces' }

  resources :background_images, only: [:index, :destroy] do
    post :bulk_create, on: :collection
  end

  resource :adult_confirmation, controller: :adult_confirmation, only: :show do
    get :confirm, on: :member
  end

  def page_mode(url, action, name, mode=:get)
    match "*id/#{url}" => action, via: [mode], as: name
  end

  post '/pages' => 'pages#update', as: :update_page
  post '/pages/preview' => 'pages#preview', as: :preview_page

  page_mode('menu_form', 'menu#form', :new_menu)
  page_mode('menu_form', 'menu#create', :create_menu, :post)
  page_mode('menu_form/(:menu_id)', 'menu#form', :edit_menu)
  page_mode('menu_form/(:menu_id)', 'menu#update', :update_menu, :put)
  page_mode('menu_form/(:menu_id)', 'menu#destroy', :destroy_menu, :delete)

  page_mode('card_form', 'cards#form', :new_card)
  page_mode('card_form', 'cards#create', :create_card, :post)
  page_mode('card_form/(:card_id)', 'cards#form', :edit_card)
  page_mode('card_form/(:card_id)', 'cards#update', :update_card, :put)
  page_mode('card_form/(:card_id)', 'cards#destroy', :destroy_card, :delete)

  match '*id' => 'pages#show', via: [:get], as: :page
  
end

app/controllers/announces_controller.rb
# encoding: utf-8
class AnnouncesController < EventsController

  def create
    authorize! :edit, Post
    @post = Post.new params[:post]
    @post.parent = params[:parent]
    @post.save
    redirect_to announces_path
  end

  def update
    authorize! :edit, Post
    post = Post.find(params[:id])
    if post.update_attributes(params[:post])
      redirect_to announce_path(post)
    else 
      render "edit"  
    end
  end


end

app/views/announces/_form.html.haml
.form-group
  %label Заголовок
  = f.text_field :title, class: 'form-control'
.form-group
  %label Краткое содержание  
  = f.text_area :preview, cols: 10, rows: 5, class: 'form-control'
.form-group
  %label Полное содержание
  = f.text_area :source, cols: 10, rows: 20, class: 'form-control'
.form-group
  %label Изображение  
  = f.file_field :image
.form-group.datetime_line
  %label Дата и время: 
  = f.datetime_select :datetime, class: 'form-control'
.form-group
  = f.submit "Сохранить", class: 'btn btn-primary'

app/views/announces/edit.html.haml
.content_block.container
  = form_for @event, :url => announce_path(@event) do |f|
    = render :partial => "form", :locals => {:f => f}
 

app/views/announces/index.html.haml
.content_block.container
  %h1 Афиша
  -if can? :edit, Post    
    = link_to 'Добавить мероприятие', new_announce_path, class: 'btn btn-success'  
  .events
    - @events.each do |event|
      .event_item
        -if event.image_stored?
          .event_image
            =image_tag event.image.thumb('200x200').url 
        .title
          = event.title
        .date 
          = event.datetime
        .preview
          = event.preview
        .links
          = link_to 'Подробнее...', announce_path(event)
  = paginate @events

app/views/announces/new.html.haml
.content_block.container
  %h1 Добавление мероприятия
  = form_for @event, :url => announces_path do |f|
    = render :partial => "form", :locals => {:f => f}

app/views/announces/show.html.haml
.event.content_block.container
  %h1=@event.title
  .text
    -if @event.image_stored?
      .event_image
        =image_tag @event.image.thumb('400x400').url
    .date 
      = @event.datetime        
    =@event.source.html_safe
  .links  
    -if can? :edit, Post
      = link_to 'Редактировать', edit_announce_path(@event), class: 'btn btn-success'
      = link_to 'Удалить', 'javascript:;', class: 'delete_link btn btn-danger', data_id: @event.id

:coffeescript
  $ ->
    $('.delete_link').on 'click', ->
      id = $(this).attr('data_id')
      if(confirm('Удалить новость?'))
        $.ajax 
          url: Routes.announce_path(id)
          type: 'DELETE'
          success: ->
            window.location.replace(Routes.announces_path)